### ISSUE TITLE
Guidance on how to connect via ssh

### ISSUE THREAD

**Issue by BransonGitomeh** [rajatchopra/openshift-origin-cartridge-cassandra#6]
everything installed wonderfuly and the instance is running, but as i tried to connect to the cassandra instance, it just regected. probably my mistake since ive never done this before. and i cant find anything to supplement what i have read on the blog. Please guide me on how to do this?

here is the activity dump on the process i used

```
[cassie-sirbranson.rhcloud.com bin]\> ps -ef|grep cassandra

4258      91209      1  7 21:05 ?        00:00:20 /var/lib/openshift/573916fd89f5cf1ad7000136/app-root/data//jdk1.8.0_05/bin/java -Xloggc:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../logs/gc.log -ea -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -Djava.net.preferIPv4Stack=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:+CMSClassUnloadingEnabled -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintPromotionFailure -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=10M -Xms256M -Xmx256M -Xmn128M -XX:+UseCondCardMark -XX:CompileCommandFile=/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../conf/hotspot_compiler -javaagent:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/jamm-0.3.0.jar -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../logs -Dcassandra.storagedir=/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../data -Dcassandra-pidfile=/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//cassandra/pid/cassandra.pid -cp /var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../conf:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../build/classes/main:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../build/classes/thrift:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/ST4-4.0.8.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/airline-0.6.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/antlr-runtime-3.5.2.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/apache-cassandra-3.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/apache-cassandra-clientutil-3.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/apache-cassandra-thrift-3.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/asm-5.0.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/cassandra-driver-core-3.0.0-shaded.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/commons-cli-1.1.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/commons-codec-1.2.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/commons-lang3-3.1.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/commons-math3-3.2.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/compress-lzf-0.8.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/concurrent-trees-2.4.0.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/concurrentlinkedhashmap-lru-1.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/disruptor-3.0.1.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/ecj-4.4.2.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/guava-18.0.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/high-scale-lib-1.0.6.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/hppc-0.5.4.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/jackson-core-asl-1.9.2.jar:/var/lib/openshift/573916fd89f5cf1ad7000136/cassandra//versions/3.4/bin/../lib/jackso
4258     163291 132905  0 21:10 pts/0    00:00:00 grep cassandra

[cassie-sirbranson.rhcloud.com bin]\> ./cqlsh

Warning: Cannot create directory at `/var/lib/openshift/573916fd89f5cf1ad7000136/.cassandra`. Command history will not be saved.

Connection error: Could not connect to localhost:9160
```

**Comment by MassimoCappellano** [comment]
Hy Branie, I don't remember very well, but I think you have to use the $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT as value of the port. Mybe if you modify the script 'cqlsh' you can give the correct value of the port to connect.

**Comment by MassimoCappellano** [comment]
Hi Branie,

in this way should work:

`./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT`

Massimo

**Comment by BransonGitomeh** [comment]
Hi @MassimoCappellano 

i did that and it threw some errors arround

``` bash
[prium-sirbranson.rhcloud.com bin]\> cd app-root/data/cassandra/bin/
[prium-sirbranson.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT

Warning: Cannot create directory at `/var/lib/openshift/575fb9490c1e665585000048/.cassandra`. Command history will not be saved.

Traceback (most recent call last):
  File "./cqlsh", line 2084, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "./cqlsh", line 2067, in main
    single_statement=options.execute)
  File "./cqlsh", line 490, in __init__
    cql_version=cqlver, transport=transport)
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 143, in connect
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 59, in __init__
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/thrifteries.py", line 159, in establish_connection
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1265, in describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1275, in recv_describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/transport/TTransport.py", line 63, in readAll
EOFError
[prium-sirbranson.rhcloud.com bin]\> 

```

hmm something is wrong somewhere.

**Comment by BransonGitomeh** [comment]
so i did a reinstall and got the same thing

``` bash
[prium-sirbranson.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT

Warning: Cannot create directory at `/var/lib/openshift/575fb9490c1e665585000048/.cassandra`. Command history will not be saved.

Traceback (most recent call last):
  File "./cqlsh", line 2084, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "./cqlsh", line 2067, in main
    single_statement=options.execute)
  File "./cqlsh", line 490, in __init__
    cql_version=cqlver, transport=transport)
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 143, in connect
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 59, in __init__
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/thrifteries.py", line 159, in establish_connection
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1265, in describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1275, in recv_describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/transport/TTransport.py", line 63, in readAll
EOFError
```

i used this `https://openshift.redhat.com/app/console/application_type/quickstart!243` to make the app(node js with auto update)

then added this catridge to it. then tried wat you said.. and boom, it produced that  error

do you have the error on your app? 

thanks . :-D

**Comment by BransonGitomeh** [comment]
so i worked out things without cqlsh  and i wrote a little thing to help anyone along the way https://github.com/BransonGitomeh/prium

but i'd love to play with `cqlsh`

**Comment by MassimoCappellano** [comment]
Hi Branie, 

about `cqlsh` first I've started from nodejs cartridge but cqlsh when I execute, says that I should have python 2.7 installed. In effect, in nodejs cartridge, the version of python was 2.6. So instead of installing the right version on python manually, I've used the python 2.7 cartridge and then added the cassandra cartdridge. In that way, was ok.

Connecting to my instance:

```
[cassandra4store-simplethings.rhcloud.com 575fff187628e17dfe000033]\> python --version
Python 2.7.8
[cassandra4store-simplethings.rhcloud.com 575fff187628e17dfe000033]\> find . -name cqlsh
find: `./.tmp': Permission denied
find: `./.sandbox': Permission denied
find: `./.ssh': Permission denied
./cassandra/versions/3.4/bin/cqlsh
[cassandra4store-simplethings.rhcloud.com 575fff187628e17dfe000033]\> cd ./cassandra/versions/3.4/bin/
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\>
[cassandra4store-simplethings.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT
Connected to cassandra4store at 127.8.29.2:19042.
[cqlsh 5.0.1 | Cassandra 3.4 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> exit;
[cassandra4store-simplethings.rhcloud.com bin]\>
```

A strange thing from your log, is that`cqlsh` on my instance is under `./cassandra/versions/3.4/bin/` . Instead on yours is in `app-root/data/cassandra/bin/` . I don't know if this could be a problem, and if it depends on https://openshift.redhat.com/app/console/application_type/quickstart!243 . I will try now. 

Massimo

**Comment by MassimoCappellano** [comment]
Another try:

Using https://openshift.redhat.com/app/console/application_type/quickstart!243 I've created a nodejs instance.
Then I've attached the cassandra instance: `rhc cartridge add https://raw.githubusercontent.com/rajatchopra/openshift-origin-cartridge-cassandra/master/metadata/manifest.yml --app paperino`

Now connected with ssh, because python is versione 2.6, I've installed python 2.7 under `$OPENSHIFT_DATA_DIR` and modified PATH variable with the path of python 2.7:

For installing python:

```
[paperino-simplethings.rhcloud.com ]\> cd $OPENSHIFT_DATA_DIR

wget --no-check-certificate https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar -xzf Python-2.7.11.tgz  
cd Python-2.7.11

./configure  
make  

[paperino-simplethings.rhcloud.com Python-2.7.11]\> pwd
/var/lib/openshift/576127af89f5cfc177000168/app-root/data/Python-2.7.11
[paperino-simplethings.rhcloud.com Python-2.7.11]\> export PATH=${OPENSHIFT_DATA_DIR}Python-2.7.11/:$PATH

[paperino-simplethings.rhcloud.com 576127af89f5cfc177000168]\> python --version
Python 2.7.11
```

Now move in `cqlsh` directory and run the `cqlsh` command:

```
[paperino-simplethings.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT

Warning: Cannot create directory at `/var/lib/openshift/576127af89f5cfc177000168/.cassandra`. Command history will not be saved.

Connected to paperino at 127.11.238.2:19042.
[cqlsh 5.0.1 | Cassandra 3.4 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh>
cqlsh>
cqlsh>
```

The problem is that for every new ssh session you have to export the PATH variable for using python 2.7.

Tell me if in this way works. Hi
Massimo

**Comment by BransonGitomeh** [comment]
hmmmmm... nice to see it working, i added python 2.7 too but. is this really a python version issue, though i do know that c\* 3.x + needs python 2.7, but im getting the same error

``` bash
[prium-sirbranson.rhcloud.com bin]\> export PATH=${OPENSHIFT_DATA_DIR}Python-2.7.11/:$PATH
[prium-sirbranson.rhcloud.com bin]\> python --version
Python 2.7.11
[prium-sirbranson.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT

Warning: Cannot create directory at `/var/lib/openshift/575fb9490c1e665585000048/.cassandra`. Command history will not be saved.

Traceback (most recent call last):
  File "./cqlsh", line 2084, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "./cqlsh", line 2067, in main
    single_statement=options.execute)
  File "./cqlsh", line 490, in __init__
    cql_version=cqlver, transport=transport)
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 143, in connect
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/connection.py", line 59, in __init__
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/thrifteries.py", line 159, in establish_connection
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1265, in describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/cql-internal-only-1.4.1.zip/cql-1.4.1/cql/cassandra/Cassandra.py", line 1275, in recv_describe_version
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
  File "/var/lib/openshift/575fb9490c1e665585000048/app-root/data/cassandra/bin/../lib/thrift-python-internal-only-0.9.1.zip/thrift/transport/TTransport.py", line 63, in readAll
EOFError
[prium-sirbranson.rhcloud.com bin]\> 
```

ill dig deeper

**Comment by MassimoCappellano** [comment]
Hi Branie,
I don't know, but very strange is that on my instance, all is under `<HOME>/cassandra/versions/3.4/bin` and I have nothing under `<HOME>/app-root/data/cassandra/bin/../lib/` like I see from trace error.

Under `<HOME>/app-root/data/` there is anything about cassandra, in my installation.

From home searching .zip like in error trace but there is not any corrispondence:

```
[paperino-simplethings.rhcloud.com 576179cf89f5cfca47000063]\> find . -name "*.zip"
find: `./.tmp': Permission denied
find: `./.sandbox': Permission denied
find: `./.ssh': Permission denied
./app-root/data/jdk1.8.0_05/javafx-src.zip
./app-root/data/jdk1.8.0_05/src.zip
./app-root/data/jdk1.8.0_05/jre/lib/deploy/ffjcext.zip
./app-root/data/Python-2.7.11/Lib/test/zipdir.zip
./cassandra/versions/3.4/lib/cassandra-driver-internal-only-3.0.0-6af642d.zip
./cassandra/versions/3.4/lib/futures-2.1.6-py2.py3-none-any.zip
./cassandra/versions/3.4/lib/six-1.7.3-py2.py3-none-any.zip
find: `./.gearstats': Permission denied
[paperino-simplethings.rhcloud.com 576179cf89f5cfca47000063]\>
```

And *.py:

```
[paperino-simplethings.rhcloud.com 576179cf89f5cfca47000063]\> find . -name "*.py"
find: `./.tmp': Permission denied
find: `./.sandbox': Permission denied
find: `./.ssh': Permission denied
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/buildbot/buildbot_run.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_sln.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_gyp.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/graphviz.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_vcproj.py
................
.................
........................................


..........................................
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/mac_tool.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/ordered_dict.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.py
./app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/setup.py
./app-root/data/Python-2.7.11/PC/VC6/build_ssl.py
./app-root/data/Python-2.7.11/PC/VC6/rmpyc.py
./app-root/data/Python-2.7.11/PC/VC6/build_tkinter.py
./app-root/data/Python-2.7.11/PC/VS7.1/build_ssl.py
........
...............
..............................
./app-root/data/Python-2.7.11/python-gdb.py
./app-root/data/Python-2.7.11/setup.py
./cassandra/versions/3.4/bin/cqlsh.py
./cassandra/versions/3.4/pylib/cqlshlib/__init__.py
./cassandra/versions/3.4/pylib/cqlshlib/copyutil.py
./cassandra/versions/3.4/pylib/cqlshlib/cql3handling.py
./cassandra/versions/3.4/pylib/cqlshlib/cqlhandling.py
./cassandra/versions/3.4/pylib/cqlshlib/displaying.py
./cassandra/versions/3.4/pylib/cqlshlib/formatting.py
./cassandra/versions/3.4/pylib/cqlshlib/helptopics.py
./cassandra/versions/3.4/pylib/cqlshlib/pylexotron.py
./cassandra/versions/3.4/pylib/cqlshlib/saferscanner.py
./cassandra/versions/3.4/pylib/cqlshlib/sslhandling.py
./cassandra/versions/3.4/pylib/cqlshlib/test/__init__.py
./cassandra/versions/3.4/pylib/cqlshlib/test/ansi_colors.py
./cassandra/versions/3.4/pylib/cqlshlib/test/basecase.py
./cassandra/versions/3.4/pylib/cqlshlib/test/cassconnect.py
./cassandra/versions/3.4/pylib/cqlshlib/test/run_cqlsh.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cql_parsing.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cqlsh_commands.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cqlsh_completion.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cqlsh_invocation.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cqlsh_output.py
./cassandra/versions/3.4/pylib/cqlshlib/test/test_cqlsh_parsing.py
./cassandra/versions/3.4/pylib/cqlshlib/test/winpty.py
./cassandra/versions/3.4/pylib/cqlshlib/tracing.py
./cassandra/versions/3.4/pylib/cqlshlib/util.py
./cassandra/versions/3.4/pylib/cqlshlib/wcwidth.py
./cassandra/versions/3.4/pylib/setup.py
find: `./.gearstats': Permission denied
[paperino-simplethings.rhcloud.com 576179cf89f5cfca47000063]\>

```

Massimo

**Comment by BransonGitomeh** [comment]
yea you were correct, i was running from the wrong directory, i ddid it all afresh and it all worked awesome. i think the cassandra dir inside `data/` is comming from installation or something. 

``` bash
[cassandra-sirbranson.rhcloud.com bin]\> ./cqlsh $OPENSHIFT_CASSANDRA_DB_HOST $OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT

Warning: Cannot create directory at `/var/lib/openshift/5764b25089f5cf93f500017e/.cassandra`. Command history will not be saved.

Connected to cassandra at 127.13.70.2:19042.
[cqlsh 5.0.1 | Cassandra 3.4 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> 

```

This is so cool ,thanks alot

**Comment by BransonGitomeh** [comment]
though i was wondering, i noticed that on every deployment i make for my node application the cassandra process has to be stopped and restarted and all that, takes some time. is there a way i can access cassandra from another application?... maybe make the cassandra port available and require auth to connect, so that that app with the catridge can be dedicated to data storage only... have you attempted something like that before? @MassimoCappellano :-D

**Comment by MassimoCappellano** [comment]
Well Branie,

this is similar to https://blog.openshift.com/sharing-database-across-applications/ 'Sharing database across application'. 

The secret is create the instance with **scale** option. 

To try, I've create an instance https://openshift.redhat.com/app/console/application_type/quickstart!243 with **scale** option (named _paperinoscale_) and then I've attached the cassandra cartridge.

If I connect to paperinoscale via ssh:

```
[paperinoscale-simplethings.rhcloud.com 5764ffc689f5cfa7f6000208]\> env | grep CASSANDRA
OPENSHIFT_CASSANDRA_DB_HOST=5765012a89f5cf6dc6000038-simplethings.rhcloud.com
OPENSHIFT_CASSANDRA_DB_GEAR_DNS=5765012a89f5cf6dc6000038-simplethings.rhcloud.com
OPENSHIFT_CASSANDRA_DB_GEAR_UUID=5765012a89f5cf6dc6000038
OPENSHIFT_CASSANDRA_NATIVE_PROXY_TRANSPORT_PORT=39507
OPENSHIFT_CASSANDRA_DB_PORT=39506
OPENSHIFT_CASSANDRA_DB_USERNAME=
OPENSHIFT_CASSANDRA_DB_PASSWORD=
OPENSHIFT_CASSANDRA_DB_URL=:@5765012a89f5cf6dc6000038-simplethings.rhcloud.com:39506/
[paperinoscale-simplethings.rhcloud.com 5764ffc689f5cfa7f6000208]\>

```

Now I've created a paperino2 instance (scale or not scale is not a problem in this case) where put the application in nodejs.

Now from **paperino2**, using value of `OPENSHIFT_CASSANDRA_DB_HOST` and `OPENSHIFT_CASSANDRA_NATIVE_PROXY_TRANSPORT_PORT` values of **paperinoscale**, try:

```
[paperino2-simplethings.rhcloud.com 576503180c1e661d10000014]\> telnet 5765012a89f5cf6dc6000038-simplethings.rhcloud.com 39507
Trying 172.16.6.156...
Connected to 5765012a89f5cf6dc6000038-simplethings.rhcloud.com.
Escape character is '^]'.

```

seems ok, can connect.

Now I can set on paperino2 (is not necessary but more simple to configure then the application) some env variable with values for connection (`OPENSHIFT_EXT_CASSANDRA_DB_HOST`, `OPENSHIFT_EXT_CASSANDRA_DB_PORT`, `OPENSHIFT_EXT_CASSANDRA_NATIVE_TRANSPORT_PORT` with values of `OPENSHIFT_CASSANDRA_DB_HOST`, `OPENSHIFT_CASSANDRA_DB_PORT`, `OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT` of paperinoscale)  :

On my computer, from command line:

```
C:\Users\CAM>rhc env-set OPENSHIFT_EXT_CASSANDRA_DB_HOST=5765012a89f5cf6dc6000038-simplethings.rhcloud.com OPENSHIFT_EXT_CASSANDRA_DB_PORT=39506 OPENSHIFT_EXT_CASSANDRA_NATIVE_TRANSPORT_PORT=39507 --app=paperino2
Setting environment variable(s) ... done

C:\Users\CAM>
```

 If you connect via ssh to paperino2:

```
[paperino2-simplethings.rhcloud.com 576503180c1e661d10000014]\> env | grep CASSANDRA
OPENSHIFT_EXT_CASSANDRA_NATIVE_TRANSPORT_PORT=39507
OPENSHIFT_EXT_CASSANDRA_DB_HOST=5765012a89f5cf6dc6000038-simplethings.rhcloud.com
OPENSHIFT_EXT_CASSANDRA_DB_PORT=39506
[paperino2-simplethings.rhcloud.com 576503180c1e661d10000014]\>
```

Now you have this variable configured 

Modifing your program, with new env variable:

```
var cassandraDriver = require('cassandra-driver');

const contactPoint1 = process.env.OPENSHIFT_EXT_CASSANDRA_DB_HOST + ":" + process.env.OPENSHIFT_EXT_CASSANDRA_DB_PORT
const contactPoint2 = process.env.OPENSHIFT_EXT_CASSANDRA_DB_HOST + ":" + process.env.OPENSHIFT_EXT_CASSANDRA_NATIVE_TRANSPORT_PORT

var connectionOptions = {
   contactPoints:[contactPoint1,contactPoint2],
   keyspace: 'system'
 };

var client = new cassandraDriver.Client(connectionOptions);

client.connect(function(e) {
  console.log(e)
  var query;
  query = "CREATE KEYSPACE IF NOT EXISTS examples WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3' }";
  return client.execute(query, function(err, res) {
    console.log("completed the check for the keyspace")
    return console.log(e, res);
  });
});
```

```
[paperino2-simplethings.rhcloud.com repo]\> node test_connection.js
null
completed the check for the keyspace
null ResultSet {
  info:
   { queriedHost: '5765012a89f5cf6dc6000038-simplethings.rhcloud.com:39507',
     triedHosts: {},
     achievedConsistency: 10,
     traceId: null,
     warnings: null,
     customPayload: null },
  rows: undefined,
  rowLength: undefined,
  columns: null,
  pageState: [Getter],
  nextPage: undefined }
^C
[paperino2-simplethings.rhcloud.com repo]\>
```

Seems work correctly.
Hi
Massimo
